import { StyleSheet } from "react-native";

// init
export const HEIGHT_STAT_GAUGE_CONTAINER = 34;
export const BORDER_RADIUS_STAT_GAUGE_CONTAINER = HEIGHT_STAT_GAUGE_CONTAINER / 2; // 17

// Spacing
export const PADDING_SEARCH_CONTAINER = 7;
export const LIST_ITEM_SPACING = 8;
export const PADDING_HORIZONTAL_ELEMENT_CARD = 20; // For screen-level padding
export const BORDER_WIDTH_CATEGORY_SELECTOR = 4;
export const PADDING_PAGINATED_WRAPPER_CONTAINER = 6;
export const MARGIN_HORIZONTAL_MODAL_CHILDREN_CONTAINER = 10;
export const MARGIN_CONTAINER_LOWEST = 16;
export const GAP_SORT_MODE_SELECTOR = 7;
export const PADDING_STANDARD = 10;
export const PADDING_BOX_CONTAINER = PADDING_STANDARD;

// calc
export const BORDER_RADIUS_CONTAINER_LOWEST = BORDER_RADIUS_STAT_GAUGE_CONTAINER + PADDING_SEARCH_CONTAINER; // 24
export const BORDER_RADIUS_STANDARD = BORDER_RADIUS_CONTAINER_LOWEST - PADDING_STANDARD; // 12

// Border Radius
export const BORDER_RADIUS_18 = 18; // More prominent rounded corners
export const BORDER_RADIUS_INF = 200;
export const BORDER_RADIUS_CATEGORY_SELECTOR = 8; // au lieu de BORDER_RADIUS_STANDARD - PADDING_PAGINATED_WRAPPER_CONTAINER; // = 6

export const BORDER_RADIUS_MODAL_CHILDREN_CONTAINER = BORDER_RADIUS_STANDARD;
export const BORDER_RADIUS_MODAL_CONTAINER =
  BORDER_RADIUS_MODAL_CHILDREN_CONTAINER + MARGIN_HORIZONTAL_MODAL_CHILDREN_CONTAINER;

export const CATEGORY_BUTTON_GALLERY_WIDTH = 60;
export const ELEMENT_PICKER_LIST_IMAGE_SIZE = CATEGORY_BUTTON_GALLERY_WIDTH;
export const ELEMENT_PICKER_LIST_IMAGE_RATIO = 1.1;

// Largeurs définies pour la colonne de gauche
export const LEFT_PANNEL_WIDTH_EXPANDED = CATEGORY_BUTTON_GALLERY_WIDTH * 4 + BORDER_WIDTH_CATEGORY_SELECTOR * 2;
export const LEFT_PANNEL_WIDTH_COLLAPSED = CATEGORY_BUTTON_GALLERY_WIDTH + BORDER_WIDTH_CATEGORY_SELECTOR * 2;

export const SET_CARD_WIDTH = 220;

export const BUTTON_SIZE = 40;
