on: workflow_dispatch
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Create update
        run: eas build --non-interactive --platform android --profile preview --local
      
      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./build-*.apk
          retention-days: 3